django_plupload/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('sample.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from sample import views as sample_views
from sample import ajax as sample_ajax

urlpatterns = [
    url(r'^$', sample_views.home, name='home'),
    url(r'^sample/ajax/get-file_filters/$', sample_ajax.get_file_filters, name='ajax_common_get_file_filters'),
    url(r'^samples/ajax/upload/$', sample_ajax.create_file, name='ajax_create_file'),
]

sample/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import ugettext as _
import os
import datetime
import random

NAME = _(u'Nombre')


def upload_reformat_name(instance, filename, related_model=None):
    """
    Format the name of the file consisting of the date, random number and extension
    The directory name: app/model/pk/directory/
    """
    name, ext = os.path.splitext(filename)
    name = '%s_%s' % (datetime.datetime.now().strftime("%Y%m%d%H%M%S"), '{:05d}'.format(random.randint(0, 99999)))

    if related_model:
        directory = '%s/%s/%s/' % (instance._meta.app_label, str(instance.__class__.__name__).lower(), str(related_model.id))

    else:
        directory = ''
    return '%s%s%s' % (directory, name, ext.lower())


def upload_file_path(instance, filename):
    return upload_reformat_name(instance, filename, instance)


class FileTypeGroup(models.Model):
    name = models.CharField(verbose_name=NAME, max_length=25, null=True, blank=True, default=None)
    order = models.PositiveSmallIntegerField(verbose_name=_(u'Orden'), blank=True, default=1000, null=True)
    codename = models.CharField(max_length=10, null=True, blank=True, default=None, unique=True)

    def __str__(self):
        return '%s %s' % (self.codename, self.name)

    class Meta:
        verbose_name = _(u'Grupo de archivos')
        verbose_name_plural = _(u'Grupos de archivos')
        ordering = ['order', 'name']


class FileExtension(models.Model):
    MIME_TYPE_CHOICES = (
        ('application', _(u'Aplicación')),
        ('audio', _(u'Audio')),
        ('font', _(u'Fuente')),
        ('image', _(u'Imagen')),
        ('text', _(u'Texto')),
        ('video', _(u'Video')),
    )
    extension = models.CharField(verbose_name=_(u'Extensión'), max_length=10, blank=True, default=None, null=True,
                                 unique=True)
    description = models.CharField(verbose_name=_(u'Descripción'), max_length=200, blank=True, default=None, null=True)
    mime_type = models.CharField(verbose_name='MIME type', choices=MIME_TYPE_CHOICES, max_length=15, blank=True,
                                 default=None, null=True)
    mime_subtype = models.CharField(verbose_name='MIME subtype', max_length=80, blank=True, default=None, null=True)

    @property
    def mime_full(self):
        return '%s/%s' % (self.mime_type, self.mime_subtype)

    def __str__(self):
        return '%s' % self.extension

    class Meta:
        verbose_name = _(u'Extensión de archivo')
        verbose_name_plural = _(u'Extensiones de archivo')
        ordering = ['extension']


class FileType(models.Model):
    file_type_group = models.ManyToManyField(FileTypeGroup, verbose_name=_(u'Grupo de archivo'))
    file_extension = models.ManyToManyField(FileExtension, verbose_name=_(u'Extensión de archivo'))
    name = models.CharField(verbose_name=NAME, max_length=50, null=True, blank=True, default=None)
    max_size = models.PositiveIntegerField(verbose_name=_(u'Tamaño máximo (KB)'), null=True, blank=True, default=1024)
    num_files = models.PositiveSmallIntegerField(verbose_name=_(u'Núm. máx.'), null=True, blank=True, default=1)
    codename = models.CharField(max_length=20, unique=True)
    order = models.PositiveSmallIntegerField(verbose_name=_(u'Orden'), blank=True, default=1000, null=True)
    is_active = models.BooleanField(verbose_name=_(u'¿Activo?'), default=True)
    image_resize = models.BooleanField(verbose_name=_(u'¿Redimensionar?'), default=True)
    image_aspect_ratio = models.BooleanField(verbose_name=_(u'¿Mantener aspecto?'), default=True)
    image_width = models.PositiveIntegerField(verbose_name=_(u'Ancho de imágen'), default=1024)
    image_height = models.PositiveIntegerField(verbose_name=_(u'Alto de imágen'), default=768)
    image_quality = models.PositiveSmallIntegerField(verbose_name=_(u'Calidad de imagen'), default=70,
                                                     validators=[MaxValueValidator(100), MinValueValidator(25)])

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = _(u'Tipo de archivo')
        verbose_name_plural = _(u'Tipos de archivo')
        ordering = ['order']


class File(models.Model):
    """ File """
    file_type = models.ForeignKey(FileType, verbose_name=_('Tipo de archivo'), blank=True, default=None, null=True, on_delete=models.SET_NULL)
    file = models.FileField(upload_to=upload_file_path, blank=True, default=None, null=True)
    description = models.CharField(verbose_name=_('Descripción'), max_length=200, blank=True, default=None, null=True)
    is_visible = models.BooleanField(verbose_name=_('Es visible'), default=False, null=False)
    order = models.PositiveSmallIntegerField(verbose_name=_('Orden'), blank=True, default=None, null=True)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Usuario'), blank=True, default=None, null=True, on_delete=models.SET_NULL)
    add_date = models.DateTimeField(verbose_name=_('Fecha de alta'), auto_now_add=True)

sample/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from sample.models import FileType, File


class FileForm(forms.ModelForm):
    file_type = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'onchange': 'generate_upload_widget(this.value)'
            },
        ),
        empty_label=_('Seleccione...'),
        label=_(u'Tipo de archivo o documento'),
        queryset=FileType.objects.all(),
        required=False
    )
    file = forms.FileField(
        widget=forms.FileInput(
            attrs={
                'class': 'hidden',
            }
        ),
        label=False,
        required=False
    )

    # file_date = forms.DateField(
    #     widget=forms.DateInput(
    #         attrs={
    #             'class': 'form-control',
    #             'readonly': ''
    #         }
    #     ),
    #     label=_(u'Fecha del archivo'),
    #     required=False
    # )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 1,
                'style': 'resize: vertical;'
            }
        ),
        label=_(u'Descripción'),
        required=False,
        error_messages={
            'required': _(u'Debe escribir la descripción del daño'),
        },
    )

    def __init__(self, *args, **kwargs):
        super(FileForm, self).__init__(*args, **kwargs)

    class Meta:
        model = File
        fields = ['file_type', 'file', 'description']

sample/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.shortcuts import render

# Create your views here.
from sample.forms import FileForm
from sample.models import File


def home(request):
    files = File.objects.all()
    form = FileForm()
    return render(request, 'home.html', {'files': files, 'form': form})

sample/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <div class="row">

        {% for file in files %}
            <div class="col-md-4">
                <h2>{{ file.description }}</h2>
                <br>
                {{ file.file }}
            </div>
        {% endfor %}


    </div>

    <div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><i class="fa fa-upload"
                                               aria-hidden="true"></i> {% trans 'Carga de archivos al sistema' %}</h4>
                </div>
                <div class="modal-body">
                    {{ form.as_p }}
                    <div id="uploader" class="hidden">
                        <p class="text-danger text-center">
                            {% trans 'Su navegador no tiene soporte para Flash, Silverlight o HTML5.' %}
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>



    <script type="text/javascript">

        var uploader = false;

        function generate_upload_widget(id_filetype) {
            // Hakai to widget if exists
            if (uploader.plupload) uploader.plupload('destroy');

            // Object for uploader widget
            uploader = $('#uploader');

            // Show and genereate when filetype selected
            if (id_filetype !== '') {

                // Obtain filters
                $.post("{% url 'ajax_common_get_file_filters' %}",
                    {
                        file_type: id_filetype,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    })
                    .done(function (data) {
                        // Generate filters
                        var mime_types_filters = [];
                        for (var I in data) mime_types_filters.push(
                            {
                                title: data[I].fields.name,
                                extensions: (data[I].fields.file_extension).join()
                            });

                        // Generate and show widget
                        uploader.removeClass('hidden');


                        uploader.plupload({
                            // Runtime settings
                            runtimes: 'html5,flash,silverlight,html4',
                            flash_swf_url: '{% static 'plupload-2.3.6/Moxie.swf' %}',
                            silverlight_xap_url: '{% static 'plupload-2.3.6/Moxie.xap' %}',
                            url: "{% url 'ajax_create_file' %}",

                            // General settings
                            multi_selection: false,
                            max_file_count: data[0].fields.num_files,
                            rename: false,
                            sortable: true,
                            dragdrop: true,

                            // Specify what files to browse for
                            filters: {
                                mime_types: mime_types_filters,
                                max_file_size: (data[0].fields.max_size) + 'kb',
                                prevent_duplicates: true
                            },

                            {#                            // Resize for image#}
                            {#                            resize : {#}
                            {#                                width: 1024,#}
                            {#                                height: 768,#}
                            {#                                quality: 90#}
                            {#                            },#}

                            // Views to activate
                            views: {
                                list: false,
                                thumbs: true,
                                active: 'list'
                            },

                            // Multipart data params
                            multipart: true,

                            // Post init events, bound after the internal events
                            init: {

                                BeforeUpload: function (up, file) {
                                    up.settings.multipart_params = {
                                        description: $('#id_description').val(),
                                        file_type: id_filetype,
                                        csrfmiddlewaretoken: '{{ csrf_token }}'

                                    };
                                },

                                FileUploaded: function (up, file, response) {
                                    // Called when file has finished uploading
                                    console.log('response: ', response);
                                },
                                UploadComplete: function (up, files) {
                                    // Called when all files are either uploaded or failed
                                    // window.location.reload();
                                }
                            }
                        });

                    });
            }
            else {
                uploader.addClass('hidden');
                uploader = false;
            }
        }

    </script>

{% endblock %}

<!-- Modal -->

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>
    
    <link rel="stylesheet" type="text/css"
      href="{% static 'plupload-2.3.6/jquery.ui.plupload/css/jquery.ui.plupload.css' %}"/>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" placeholder="Email" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>
            </form>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a
            jumbotron and three supporting pieces of content. Use it as a starting point to create something more
            unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button" data-toggle="modal" data-target="#myModal">Upload file &raquo;</a></p>
    </div>
</div>

<div class="container">
    {% block content %}
        <!-- Example row of columns -->
        
    {% endblock %}
    <hr>

    <footer>
        <p>&copy; 2016 Company, Inc.</p>
    </footer>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>

    <!-- plupload -->
    <script type="text/javascript" src="{% static 'plupload-2.3.6/plupload.full.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'plupload-2.3.6/jquery.ui.plupload/jquery.ui.plupload.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plupload-2.3.6/i18n/es.js' %}"></script>
</body>
</html>